### ISSUE TITLE
TODO VISA

### ISSUE THREAD

**Issue by akevalion** [akevalion/life_cost#1]
Milton
- [x] 1. copia escaneada del pasaporte
- [x] 2. milton cv es
- [x] 3. certificado de antecedentes penales milton francia
- [x] 4. certificado de antecedentes penales milton bolivia
- [x] 5. declaracion de 5 anios milton
- [x] 6. titulo milton
- [x] 7. cartas de recomendacion de inria
- [x] 8. carta de recomendacion ObjectProfile
- [x] 9. documentos de acreditacion de formacion y experiencia
- [x] 10. Permiso de residencia de Francia

Claudia
- [x] 1. copia escaneada del pasaporte
- [x] 2. certificado de matrimonio
- [x] 3. certificado de antecedentes penales clau
- [x] 4. declaracion de 5 anios clau

Apostillas de Francia
- [x] certificado de antecedentes penales milton
- [x] traducir antecedentes a espaniol

Apostillas de Bolivia
- [x] certificado de matrimonio
- [x] certificado de antecedentes penales clau
- [x] certificado de antecedentes penales milton
- [x] titulo milton

**Comment by akevalion** [comment]
done
